IF DB_ID('QL_THUVIEN') IS NULL
    CREATE DATABASE QL_THUVIEN;
GO
USE QL_THUVIEN;
GO

IF OBJECT_ID('PHIEUPHAT', 'U') IS NOT NULL DROP TABLE PHIEUPHAT;
IF OBJECT_ID('CHITIET_PHIEUMUON', 'U') IS NOT NULL DROP TABLE CHITIET_PHIEUMUON;
IF OBJECT_ID('PHIEUMUON', 'U') IS NOT NULL DROP TABLE PHIEUMUON;
IF OBJECT_ID('SACH', 'U') IS NOT NULL DROP TABLE SACH;
IF OBJECT_ID('DOCGIA', 'U') IS NOT NULL DROP TABLE DOCGIA;
IF OBJECT_ID('NHANVIEN', 'U') IS NOT NULL DROP TABLE NHANVIEN;
GO

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    SDT VARCHAR(15),
    DiaChi NVARCHAR(255),
    VaiTro NVARCHAR(20) CHECK (VaiTro IN ('Manager', 'Staff')),
    Username VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL DEFAULT '123456'
);
GO

CREATE TABLE DOCGIA (
    MaDG VARCHAR(10) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    DiaChi NVARCHAR(255),
    SDT VARCHAR(15),
    Password VARCHAR(255) NOT NULL DEFAULT '123456'
);
GO

CREATE TABLE SACH (
    MaSach VARCHAR(10) PRIMARY KEY,
    TenSach NVARCHAR(255) UNIQUE NOT NULL,
    TacGia NVARCHAR(100),
    NamXB INT,
    GiaBia DECIMAL(18,2),
    SoLuong INT CHECK (SoLuong >= 0),
    MaVach VARCHAR(50) UNIQUE,
    MoTa NVARCHAR(500)
);
GO

CREATE TABLE PHIEUMUON (
    MaPM VARCHAR(10) PRIMARY KEY,
    MaDG VARCHAR(10) NOT NULL,
    MaNV VARCHAR(10) NOT NULL,
    NgayMuon DATE NOT NULL,
    FOREIGN KEY (MaDG) REFERENCES DOCGIA(MaDG),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);
GO

CREATE TABLE CHITIET_PHIEUMUON (
    MaCT VARCHAR(10) PRIMARY KEY,
    MaPM VARCHAR(10) NOT NULL,
    MaSach VARCHAR(10) NOT NULL,
    NgayPhaiTra DATE NOT NULL,
    NgayTra DATE NULL,
    TrangThai NVARCHAR(20) CHECK (TrangThai IN ('DangMuon', 'DaTra', 'QuaHan')),
    FOREIGN KEY (MaPM) REFERENCES PHIEUMUON(MaPM),
    FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
);
GO

CREATE TABLE PHIEUPHAT (
    MaPhat VARCHAR(10) PRIMARY KEY,
    MaCT VARCHAR(10) UNIQUE,
    SoTienPhat DECIMAL(18,2),
    LyDo NVARCHAR(255),
    FOREIGN KEY (MaCT) REFERENCES CHITIET_PHIEUMUON(MaCT)
);
GO

INSERT INTO NHANVIEN (MaNV, HoTen, NgaySinh, SDT, DiaChi, VaiTro, Username, Password) VALUES
('NV001', N'Nguyen Van A', '1995-05-12', '0987654321', N'Ha Noi', 'Staff', 'nv001', '123456'),
('NV002', N'Tran Thi B', '1990-08-03', '0912345678', N'Ha Noi', 'Manager', 'nv002', '123456');

INSERT INTO DOCGIA (MaDG, HoTen, NgaySinh, DiaChi, SDT, Password) VALUES
('DG001', N'Le Minh Quan', '2004-01-15', N'Ha Noi', '0901111222', '123456'),
('DG002', N'Pham Thu Ha', '2003-09-20', N'Hai Phong', '0903333444', '123456');

INSERT INTO SACH (MaSach, TenSach, TacGia, NamXB, GiaBia, SoLuong, MaVach, MoTa) VALUES
('S001', N'Lap trinh Java', N'Nguyen Van C', 2024, 150000, 3, 'BC-S001', N'Giao trinh Java co ban den nang cao'),
('S002', N'Co so du lieu', N'Tran Van D', 2023, 180000, 2, 'BC-S002', N'SQL va thiet ke CSDL'),
('S003', N'Phan tich thiet ke he thong', N'Le Van E', 2022, 200000, 4, 'BC-S003', N'UML va phan tich nghiep vu');
GO
